# Generated by Django 4.2 on 2024-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('c', 'Comedia'), ('F', 'Familiar'), ('A', 'Animación'), ('T', 'Terror'), ('S', 'Suspenso'), ('H', 'Heroes')], max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('year', models.BigIntegerField(max_length=4)),
                ('synopsis', models.CharField(max_length=100)),
            ],
        ),
    ]
